GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON FUNCTION "public"."_extract_domain"("u" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."_extract_domain"("u" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."_extract_domain"("u" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."auto_close_stale_sessions"() TO "anon";
GRANT ALL ON FUNCTION "public"."auto_close_stale_sessions"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."auto_close_stale_sessions"() TO "service_role";
GRANT ALL ON FUNCTION "public"."calculate_employee_compliance"("target_user_id" "uuid", "target_month" "date") TO "anon";
GRANT ALL ON FUNCTION "public"."calculate_employee_compliance"("target_user_id" "uuid", "target_month" "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."calculate_employee_compliance"("target_user_id" "uuid", "target_month" "date") TO "service_role";
GRANT ALL ON FUNCTION "public"."close_user_active_sessions"("p_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."close_user_active_sessions"("p_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."close_user_active_sessions"("p_user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."close_user_active_sessions"("p_user_id" "uuid", "p_device_id" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."close_user_active_sessions"("p_user_id" "uuid", "p_device_id" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."close_user_active_sessions"("p_user_id" "uuid", "p_device_id" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."configure_service_role_key"("new_service_key" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."configure_service_role_key"("new_service_key" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."configure_service_role_key"("new_service_key" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_compliance_warning"("target_user_id" "uuid", "target_month" "date") TO "anon";
GRANT ALL ON FUNCTION "public"."create_compliance_warning"("target_user_id" "uuid", "target_month" "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_compliance_warning"("target_user_id" "uuid", "target_month" "date") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_fraud_alert_notification"("alert_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."create_fraud_alert_notification"("alert_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_fraud_alert_notification"("alert_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_notification"("target_user_id" "uuid", "notification_type" "text", "notification_title" "text", "notification_message" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."create_notification"("target_user_id" "uuid", "notification_type" "text", "notification_title" "text", "notification_message" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_notification"("target_user_id" "uuid", "notification_type" "text", "notification_title" "text", "notification_message" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."create_sample_analysis"("p_user_id" "uuid", "p_analysis_date" "date") TO "anon";
GRANT ALL ON FUNCTION "public"."create_sample_analysis"("p_user_id" "uuid", "p_analysis_date" "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_sample_analysis"("p_user_id" "uuid", "p_analysis_date" "date") TO "service_role";
GRANT ALL ON FUNCTION "public"."cron_run_ai_analysis"() TO "anon";
GRANT ALL ON FUNCTION "public"."cron_run_ai_analysis"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."cron_run_ai_analysis"() TO "service_role";
GRANT ALL ON FUNCTION "public"."dismiss_warning"("warning_id" "uuid", "target_user_id" "uuid", "response" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."dismiss_warning"("warning_id" "uuid", "target_user_id" "uuid", "response" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."dismiss_warning"("warning_id" "uuid", "target_user_id" "uuid", "response" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."find_duplicate_screenshots"("input_user_id" "uuid", "input_duplicate_hash" "text", "hours_back" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."find_duplicate_screenshots"("input_user_id" "uuid", "input_duplicate_hash" "text", "hours_back" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."find_duplicate_screenshots"("input_user_id" "uuid", "input_duplicate_hash" "text", "hours_back" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."find_similar_screenshots"("input_user_id" "uuid", "input_hash" "text", "hours_back" integer, "max_results" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."find_similar_screenshots"("input_user_id" "uuid", "input_hash" "text", "hours_back" integer, "max_results" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."find_similar_screenshots"("input_user_id" "uuid", "input_hash" "text", "hours_back" integer, "max_results" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."generate_email_content_for_config"("config_record" "record", "report_data" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."generate_email_content_for_config"("config_record" "record", "report_data" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_email_content_for_config"("config_record" "record", "report_data" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."generate_employee_insights"("p_period_type" "text", "p_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."generate_employee_insights"("p_period_type" "text", "p_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_employee_insights"("p_period_type" "text", "p_user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."generate_report_data_for_config"("config_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."generate_report_data_for_config"("config_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."generate_report_data_for_config"("config_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_active_warnings_for_user"("target_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_active_warnings_for_user"("target_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_active_warnings_for_user"("target_user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_app_settings"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_app_settings"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_app_settings"() TO "service_role";
GRANT ALL ON FUNCTION "public"."get_cron_job_status"("p_jobname" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_cron_job_status"("p_jobname" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_cron_job_status"("p_jobname" "text") TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_current_user_context"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."get_current_user_context"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_current_user_context"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_current_user_context"() TO "service_role";
GRANT ALL ON FUNCTION "public"."get_due_reports"("check_time" timestamp with time zone) TO "anon";
GRANT ALL ON FUNCTION "public"."get_due_reports"("check_time" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_due_reports"("check_time" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."get_employee_finance_summary"("target_month" "date") TO "anon";
GRANT ALL ON FUNCTION "public"."get_employee_finance_summary"("target_month" "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_employee_finance_summary"("target_month" "date") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_fraud_alerts_summary"("days_back" integer, "target_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_fraud_alerts_summary"("days_back" integer, "target_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_fraud_alerts_summary"("days_back" integer, "target_user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_organization_by_slug"("org_slug" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_organization_by_slug"("org_slug" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_organization_by_slug"("org_slug" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_organization_cost_insights"("p_organization_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_organization_cost_insights"("p_organization_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_organization_cost_insights"("p_organization_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_privacy_risk_screenshots"("input_user_id" "uuid", "risk_threshold" integer, "hours_back" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."get_privacy_risk_screenshots"("input_user_id" "uuid", "risk_threshold" integer, "hours_back" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_privacy_risk_screenshots"("input_user_id" "uuid", "risk_threshold" integer, "hours_back" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."get_recent_http_stats"("p_since" timestamp with time zone) TO "anon";
GRANT ALL ON FUNCTION "public"."get_recent_http_stats"("p_since" timestamp with time zone) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_recent_http_stats"("p_since" timestamp with time zone) TO "service_role";
GRANT ALL ON FUNCTION "public"."get_user_organization_id"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_organization_id"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_organization_id"("user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_user_role"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_role"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_role"() TO "service_role";
GRANT ALL ON FUNCTION "public"."get_user_role"("uid" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_user_role"("uid" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_user_role"("uid" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."get_worker_status"("worker_type_param" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_worker_status"("worker_type_param" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_worker_status"("worker_type_param" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."hamming_distance_hex64"("a_hex" "text", "b_hex" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."hamming_distance_hex64"("a_hex" "text", "b_hex" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."hamming_distance_hex64"("a_hex" "text", "b_hex" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";
GRANT ALL ON FUNCTION "public"."infer_idle_screenshots"() TO "anon";
GRANT ALL ON FUNCTION "public"."infer_idle_screenshots"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."infer_idle_screenshots"() TO "service_role";
GRANT ALL ON FUNCTION "public"."is_org_admin"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_org_admin"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_org_admin"("user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."is_super_admin"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_super_admin"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_super_admin"("user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."log_report_send"("p_config_id" "uuid", "p_status" "text", "p_recipient_count" integer, "p_error_message" "text", "p_email_service_id" "text", "p_report_data" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."log_report_send"("p_config_id" "uuid", "p_status" "text", "p_recipient_count" integer, "p_error_message" "text", "p_email_service_id" "text", "p_report_data" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."log_report_send"("p_config_id" "uuid", "p_status" "text", "p_recipient_count" integer, "p_error_message" "text", "p_email_service_id" "text", "p_report_data" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."log_warning_shown"("warning_id" "uuid", "target_user_id" "uuid", "action" "text", "response" "text", "warning_context" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."log_warning_shown"("warning_id" "uuid", "target_user_id" "uuid", "action" "text", "response" "text", "warning_context" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."log_warning_shown"("warning_id" "uuid", "target_user_id" "uuid", "action" "text", "response" "text", "warning_context" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."mark_screenshot_for_reanalysis"("screenshot_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."mark_screenshot_for_reanalysis"("screenshot_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."mark_screenshot_for_reanalysis"("screenshot_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."notify_employee_status_change"() TO "anon";
GRANT ALL ON FUNCTION "public"."notify_employee_status_change"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."notify_employee_status_change"() TO "service_role";
GRANT ALL ON FUNCTION "public"."notify_new_employee_welcome"() TO "anon";
GRANT ALL ON FUNCTION "public"."notify_new_employee_welcome"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."notify_new_employee_welcome"() TO "service_role";
GRANT ALL ON FUNCTION "public"."pause_user"("target_user_id" "uuid", "admin_user_id" "uuid", "reason" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."pause_user"("target_user_id" "uuid", "admin_user_id" "uuid", "reason" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."pause_user"("target_user_id" "uuid", "admin_user_id" "uuid", "reason" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."process_notification_queue"("batch_limit" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."process_notification_queue"("batch_limit" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."process_notification_queue"("batch_limit" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."process_pending_screenshots"("batch_limit" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."process_pending_screenshots"("batch_limit" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."process_pending_screenshots"("batch_limit" integer) TO "service_role";
GRANT ALL ON FUNCTION "public"."process_scheduled_reports_direct"("report_type" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."process_scheduled_reports_direct"("report_type" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."process_scheduled_reports_direct"("report_type" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."process_subject_template"("template" "text", "report_data" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."process_subject_template"("template" "text", "report_data" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."process_subject_template"("template" "text", "report_data" "jsonb") TO "service_role";
GRANT ALL ON FUNCTION "public"."run_ai_employee_analysis"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_ai_employee_analysis"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_ai_employee_analysis"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_ai_screenshot_analyzer"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_ai_screenshot_analyzer"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_ai_screenshot_analyzer"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_insights_generator"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_insights_generator"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_insights_generator"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_insights_generator_per_org"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_insights_generator_per_org"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_insights_generator_per_org"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_notification_processor"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_notification_processor"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_notification_processor"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_screenshot_cleanup"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_screenshot_cleanup"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_screenshot_cleanup"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_screenshot_processor"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_screenshot_processor"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_screenshot_processor"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_system_health_alert"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_system_health_alert"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_system_health_alert"() TO "service_role";
GRANT ALL ON FUNCTION "public"."run_vision_validator"() TO "anon";
GRANT ALL ON FUNCTION "public"."run_vision_validator"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."run_vision_validator"() TO "service_role";
GRANT ALL ON FUNCTION "public"."send_daily_hours_alert_per_org"() TO "anon";
GRANT ALL ON FUNCTION "public"."send_daily_hours_alert_per_org"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."send_daily_hours_alert_per_org"() TO "service_role";
GRANT ALL ON FUNCTION "public"."send_email_reports_per_org"("report_type" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."send_email_reports_per_org"("report_type" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."send_email_reports_per_org"("report_type" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."send_email_via_resend"("to_emails" "text"[], "subject" "text", "html_content" "text", "from_email" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."send_email_via_resend"("to_emails" "text"[], "subject" "text", "html_content" "text", "from_email" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."send_email_via_resend"("to_emails" "text"[], "subject" "text", "html_content" "text", "from_email" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."set_organization_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_organization_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_organization_id"() TO "service_role";
GRANT ALL ON FUNCTION "public"."sync_screenshot_timestamps"() TO "anon";
GRANT ALL ON FUNCTION "public"."sync_screenshot_timestamps"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."sync_screenshot_timestamps"() TO "service_role";
GRANT ALL ON FUNCTION "public"."trigger_employee_notification"("employee_id" "uuid", "change_type" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."trigger_employee_notification"("employee_id" "uuid", "change_type" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."trigger_employee_notification"("employee_id" "uuid", "change_type" "text") TO "service_role";
GRANT ALL ON FUNCTION "public"."trigger_fraud_alert_notification"() TO "anon";
GRANT ALL ON FUNCTION "public"."trigger_fraud_alert_notification"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."trigger_fraud_alert_notification"() TO "service_role";
GRANT ALL ON FUNCTION "public"."unpause_user"("target_user_id" "uuid", "admin_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."unpause_user"("target_user_id" "uuid", "admin_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."unpause_user"("target_user_id" "uuid", "admin_user_id" "uuid") TO "service_role";
GRANT ALL ON FUNCTION "public"."update_ai_analysis_metrics"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_ai_analysis_metrics"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_ai_analysis_metrics"() TO "service_role";
GRANT ALL ON FUNCTION "public"."update_app_settings_timestamp"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_app_settings_timestamp"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_app_settings_timestamp"() TO "service_role";
GRANT ALL ON FUNCTION "public"."update_consecutive_duplicate_count"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_consecutive_duplicate_count"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_consecutive_duplicate_count"() TO "service_role";
GRANT ALL ON FUNCTION "public"."update_manual_hours_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_manual_hours_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_manual_hours_updated_at"() TO "service_role";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."url_logs_view_insert"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."url_logs_view_insert"() TO "anon";
GRANT ALL ON FUNCTION "public"."url_logs_view_insert"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."url_logs_view_insert"() TO "service_role";
GRANT ALL ON FUNCTION "public"."url_logs_view_ud_block"() TO "anon";
GRANT ALL ON FUNCTION "public"."url_logs_view_ud_block"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."url_logs_view_ud_block"() TO "service_role";
GRANT ALL ON FUNCTION "public"."validate_user_organization"("user_email" "text", "org_slug" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."validate_user_organization"("user_email" "text", "org_slug" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."validate_user_organization"("user_email" "text", "org_slug" "text") TO "service_role";
GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";
GRANT ALL ON TABLE "public"."active_employees" TO "anon";
GRANT ALL ON TABLE "public"."active_employees" TO "authenticated";
GRANT ALL ON TABLE "public"."active_employees" TO "service_role";
GRANT ALL ON TABLE "public"."activities" TO "anon";
GRANT ALL ON TABLE "public"."activities" TO "authenticated";
GRANT ALL ON TABLE "public"."activities" TO "service_role";
GRANT ALL ON TABLE "public"."admin_alerts" TO "anon";
GRANT ALL ON TABLE "public"."admin_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."admin_alerts" TO "service_role";
GRANT ALL ON TABLE "public"."ai_analysis_metrics" TO "anon";
GRANT ALL ON TABLE "public"."ai_analysis_metrics" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_analysis_metrics" TO "service_role";
GRANT ALL ON TABLE "public"."ai_analysis_queue" TO "anon";
GRANT ALL ON TABLE "public"."ai_analysis_queue" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_analysis_queue" TO "service_role";
GRANT ALL ON TABLE "public"."screenshots" TO "anon";
GRANT ALL ON TABLE "public"."screenshots" TO "authenticated";
GRANT ALL ON TABLE "public"."screenshots" TO "service_role";
GRANT ALL ON TABLE "public"."ai_analysis_stats" TO "anon";
GRANT ALL ON TABLE "public"."ai_analysis_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_analysis_stats" TO "service_role";
GRANT ALL ON TABLE "public"."ai_employee_insights" TO "anon";
GRANT ALL ON TABLE "public"."ai_employee_insights" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_employee_insights" TO "service_role";
GRANT ALL ON TABLE "public"."ai_user_patterns" TO "anon";
GRANT ALL ON TABLE "public"."ai_user_patterns" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_user_patterns" TO "service_role";
GRANT ALL ON TABLE "public"."alert_summary" TO "anon";
GRANT ALL ON TABLE "public"."alert_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."alert_summary" TO "service_role";
GRANT ALL ON TABLE "public"."app_logs" TO "anon";
GRANT ALL ON TABLE "public"."app_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."app_logs" TO "service_role";
GRANT ALL ON TABLE "public"."app_settings" TO "anon";
GRANT ALL ON TABLE "public"."app_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."app_settings" TO "service_role";
GRANT ALL ON TABLE "public"."app_url_activity" TO "anon";
GRANT ALL ON TABLE "public"."app_url_activity" TO "authenticated";
GRANT ALL ON TABLE "public"."app_url_activity" TO "service_role";
GRANT ALL ON TABLE "public"."app_usage_analytics" TO "anon";
GRANT ALL ON TABLE "public"."app_usage_analytics" TO "authenticated";
GRANT ALL ON TABLE "public"."app_usage_analytics" TO "service_role";
GRANT ALL ON TABLE "public"."time_logs" TO "anon";
GRANT ALL ON TABLE "public"."time_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."time_logs" TO "service_role";
GRANT ALL ON TABLE "public"."daily_activity_summary" TO "anon";
GRANT ALL ON TABLE "public"."daily_activity_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."daily_activity_summary" TO "service_role";
GRANT ALL ON TABLE "public"."duplicate_screenshots_summary" TO "anon";
GRANT ALL ON TABLE "public"."duplicate_screenshots_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."duplicate_screenshots_summary" TO "service_role";
GRANT ALL ON TABLE "public"."employee_analysis_requests" TO "anon";
GRANT ALL ON TABLE "public"."employee_analysis_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_analysis_requests" TO "service_role";
GRANT ALL ON TABLE "public"."employee_behavioral_patterns" TO "anon";
GRANT ALL ON TABLE "public"."employee_behavioral_patterns" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_behavioral_patterns" TO "service_role";
GRANT ALL ON TABLE "public"."employee_comprehensive_analysis" TO "anon";
GRANT ALL ON TABLE "public"."employee_comprehensive_analysis" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_comprehensive_analysis" TO "service_role";
GRANT ALL ON TABLE "public"."employee_daily_activities" TO "anon";
GRANT ALL ON TABLE "public"."employee_daily_activities" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_daily_activities" TO "service_role";
GRANT ALL ON TABLE "public"."employee_deductions" TO "anon";
GRANT ALL ON TABLE "public"."employee_deductions" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_deductions" TO "service_role";
GRANT ALL ON TABLE "public"."employee_management_insights" TO "anon";
GRANT ALL ON TABLE "public"."employee_management_insights" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_management_insights" TO "service_role";
GRANT ALL ON TABLE "public"."employee_project_assignments" TO "anon";
GRANT ALL ON TABLE "public"."employee_project_assignments" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_project_assignments" TO "service_role";
GRANT ALL ON TABLE "public"."employee_warnings" TO "anon";
GRANT ALL ON TABLE "public"."employee_warnings" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_warnings" TO "service_role";
GRANT ALL ON TABLE "public"."employee_working_standards" TO "anon";
GRANT ALL ON TABLE "public"."employee_working_standards" TO "authenticated";
GRANT ALL ON TABLE "public"."employee_working_standards" TO "service_role";
GRANT ALL ON TABLE "public"."fraud_alerts" TO "anon";
GRANT ALL ON TABLE "public"."fraud_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."fraud_alerts" TO "service_role";
GRANT ALL ON TABLE "public"."idle_logs" TO "anon";
GRANT ALL ON TABLE "public"."idle_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."idle_logs" TO "service_role";
GRANT ALL ON TABLE "public"."idle_analytics" TO "anon";
GRANT ALL ON TABLE "public"."idle_analytics" TO "authenticated";
GRANT ALL ON TABLE "public"."idle_analytics" TO "service_role";
GRANT ALL ON TABLE "public"."inactive_employees" TO "anon";
GRANT ALL ON TABLE "public"."inactive_employees" TO "authenticated";
GRANT ALL ON TABLE "public"."inactive_employees" TO "service_role";
GRANT ALL ON TABLE "public"."latest_employee_analysis" TO "anon";
GRANT ALL ON TABLE "public"."latest_employee_analysis" TO "authenticated";
GRANT ALL ON TABLE "public"."latest_employee_analysis" TO "service_role";
GRANT ALL ON TABLE "public"."manual_hours" TO "anon";
GRANT ALL ON TABLE "public"."manual_hours" TO "authenticated";
GRANT ALL ON TABLE "public"."manual_hours" TO "service_role";
GRANT ALL ON TABLE "public"."manual_hours_audit" TO "anon";
GRANT ALL ON TABLE "public"."manual_hours_audit" TO "authenticated";
GRANT ALL ON TABLE "public"."manual_hours_audit" TO "service_role";
GRANT ALL ON TABLE "public"."notification_log" TO "anon";
GRANT ALL ON TABLE "public"."notification_log" TO "authenticated";
GRANT ALL ON TABLE "public"."notification_log" TO "service_role";
GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";
GRANT ALL ON TABLE "public"."organizations" TO "anon";
GRANT ALL ON TABLE "public"."organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations" TO "service_role";
GRANT ALL ON TABLE "public"."perceptual_hash_duplicates" TO "anon";
GRANT ALL ON TABLE "public"."perceptual_hash_duplicates" TO "authenticated";
GRANT ALL ON TABLE "public"."perceptual_hash_duplicates" TO "service_role";
GRANT ALL ON TABLE "public"."productivity_metrics" TO "anon";
GRANT ALL ON TABLE "public"."productivity_metrics" TO "authenticated";
GRANT ALL ON TABLE "public"."productivity_metrics" TO "service_role";
GRANT ALL ON TABLE "public"."projects" TO "anon";
GRANT ALL ON TABLE "public"."projects" TO "authenticated";
GRANT ALL ON TABLE "public"."projects" TO "service_role";
GRANT ALL ON TABLE "public"."report_configurations" TO "anon";
GRANT ALL ON TABLE "public"."report_configurations" TO "authenticated";
GRANT ALL ON TABLE "public"."report_configurations" TO "service_role";
GRANT ALL ON TABLE "public"."report_history" TO "anon";
GRANT ALL ON TABLE "public"."report_history" TO "authenticated";
GRANT ALL ON TABLE "public"."report_history" TO "service_role";
GRANT ALL ON TABLE "public"."report_recipients" TO "anon";
GRANT ALL ON TABLE "public"."report_recipients" TO "authenticated";
GRANT ALL ON TABLE "public"."report_recipients" TO "service_role";
GRANT ALL ON TABLE "public"."report_types" TO "anon";
GRANT ALL ON TABLE "public"."report_types" TO "authenticated";
GRANT ALL ON TABLE "public"."report_types" TO "service_role";
GRANT ALL ON TABLE "public"."screenshot_comments" TO "anon";
GRANT ALL ON TABLE "public"."screenshot_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."screenshot_comments" TO "service_role";
GRANT ALL ON TABLE "public"."screenshot_deletions" TO "anon";
GRANT ALL ON TABLE "public"."screenshot_deletions" TO "authenticated";
GRANT ALL ON TABLE "public"."screenshot_deletions" TO "service_role";
GRANT ALL ON TABLE "public"."settings" TO "anon";
GRANT ALL ON TABLE "public"."settings" TO "authenticated";
GRANT ALL ON TABLE "public"."settings" TO "service_role";
GRANT ALL ON TABLE "public"."suspicious_activity" TO "anon";
GRANT ALL ON TABLE "public"."suspicious_activity" TO "authenticated";
GRANT ALL ON TABLE "public"."suspicious_activity" TO "service_role";
GRANT ALL ON TABLE "public"."system_checks" TO "anon";
GRANT ALL ON TABLE "public"."system_checks" TO "authenticated";
GRANT ALL ON TABLE "public"."system_checks" TO "service_role";
GRANT ALL ON TABLE "public"."system_logs" TO "anon";
GRANT ALL ON TABLE "public"."system_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."system_logs" TO "service_role";
GRANT ALL ON TABLE "public"."tasks" TO "anon";
GRANT ALL ON TABLE "public"."tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."tasks" TO "service_role";
GRANT ALL ON TABLE "public"."team_leader_assignments" TO "anon";
GRANT ALL ON TABLE "public"."team_leader_assignments" TO "authenticated";
GRANT ALL ON TABLE "public"."team_leader_assignments" TO "service_role";
GRANT ALL ON TABLE "public"."url_logs" TO "anon";
GRANT ALL ON TABLE "public"."url_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."url_logs" TO "service_role";
GRANT ALL ON TABLE "public"."url_logs_old" TO "anon";
GRANT ALL ON TABLE "public"."url_logs_old" TO "authenticated";
GRANT ALL ON TABLE "public"."url_logs_old" TO "service_role";
GRANT ALL ON TABLE "public"."url_usage_analytics" TO "anon";
GRANT ALL ON TABLE "public"."url_usage_analytics" TO "authenticated";
GRANT ALL ON TABLE "public"."url_usage_analytics" TO "service_role";
GRANT ALL ON TABLE "public"."user_agent_versions" TO "anon";
GRANT ALL ON TABLE "public"."user_agent_versions" TO "authenticated";
GRANT ALL ON TABLE "public"."user_agent_versions" TO "service_role";
GRANT ALL ON TABLE "public"."user_invites" TO "anon";
GRANT ALL ON TABLE "public"."user_invites" TO "authenticated";
GRANT ALL ON TABLE "public"."user_invites" TO "service_role";
GRANT ALL ON TABLE "public"."vision_analysis_metrics" TO "anon";
GRANT ALL ON TABLE "public"."vision_analysis_metrics" TO "authenticated";
GRANT ALL ON TABLE "public"."vision_analysis_metrics" TO "service_role";
GRANT ALL ON TABLE "public"."vision_feature_flags" TO "anon";
GRANT ALL ON TABLE "public"."vision_feature_flags" TO "authenticated";
GRANT ALL ON TABLE "public"."vision_feature_flags" TO "service_role";
GRANT ALL ON TABLE "public"."warning_logs" TO "anon";
GRANT ALL ON TABLE "public"."warning_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."warning_logs" TO "service_role";
GRANT ALL ON TABLE "public"."warning_messages" TO "anon";
GRANT ALL ON TABLE "public"."warning_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."warning_messages" TO "service_role";
GRANT ALL ON TABLE "public"."warning_templates" TO "anon";
GRANT ALL ON TABLE "public"."warning_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."warning_templates" TO "service_role";
GRANT ALL ON TABLE "public"."worker_status" TO "anon";
GRANT ALL ON TABLE "public"."worker_status" TO "authenticated";
GRANT ALL ON TABLE "public"."worker_status" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
